FROM node:alpine

WORKDIR /usr/src/app
ENV HOME=/usr/src/app
ENV PATH /app/node_modules/.bin:$PATH

RUN rm -rf node_modules/

COPY ./frontend/package.json ./package.json
COPY ./frontend/package-lock.json ./package-lock.json
RUN npm ci

# RUN npm i @angular/cli -g
# RUN npm i -D @angular-builders/custom-webpack

EXPOSE 4200

USER 1000
