FROM node:alpine

WORKDIR /usr/src/app
ENV HOME=/usr/src/app

RUN rm -rf node_modules/

RUN npm i --save

RUN npm i npm@latest -g
COPY ./frontend/package.json ./
COPY ./frontend/package-lock.json ./
RUN npm install

RUN yarn global add @angular/cli


EXPOSE 4200

USER 1000
