version: '3.7'

services:
  prop_backend_requests:
    container_name: prop_backend_requests
    build:
      context: .
      dockerfile: ./requests/Dockerfile
      args:
        - BACKEND_APIKEY=${BACKEND_APIKEY}
    image: prop_backend_requests
    ports:
      - '5004:5000'
    expose:
      - '80'
      - '5004'
    command: bash -c "cron && python3 /data/main.py run -h 0.0.0.0"
    volumes:
      - type: volume
        source: prop_docker_volume
        target: /data
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
      - .env.fixedVariables
    privileged: true
    depends_on:
      - prop_backend_redis

  prop_backend_worker:
    container_name: prop_backend_worker
    image: prop_backend_worker
    build:
      context: .
      dockerfile: ./requests/Dockerfile
      args:
        - BACKEND_APIKEY=${BACKEND_APIKEY}
    command: rq worker --url redis://prop_backend_redis:6379/0
    volumes:
      - type: volume
        source: prop_docker_volume
        target: /data
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
      - .env.fixedVariables
    privileged: true
    depends_on:
      - prop_backend_redis
      - prop_backend_requests
    links:
      - prop_backend_redis

  prop_backend_dashboard:
    container_name: prop_backend_dashboard
    image: eoranged/rq-dashboard
    ports:
      - '9181:9181'
    environment:
      - RQ_DASHBOARD_REDIS_URL=redis://prop_backend_redis:6379
      - RQ_DASHBOARD_USERNAME=rq
      - RQ_DASHBOARD_PASSWORD=password
      - RQ_DASHBOARD_interval=30000
    depends_on:
      - prop_backend_redis
      - prop_backend_requests
    links:
      - prop_backend_redis

  prop_backend_clustalw:
    container_name: prop_backend_clustalw
    build:
      context: .
      dockerfile: ./algorithms/Dockerfile_clustalw
    image: prop_backend_clustalw
    # volumes:
    #   - type: volume
    #     source: prop_docker_volume
    #     target: /data
    links:
      - prop_backend_requests
      - prop_backend_worker

  prop_backend_mafft:
    container_name: prop_backend_mafft
    build:
      context: .
      dockerfile: ./algorithms/Dockerfile_mafft
    image: prop_backend_mafft
    volumes:
      - type: volume
        source: prop_docker_volume
        target: /data
    links:
      - prop_backend_requests
      - prop_backend_worker

  prop_backend_redis:
    container_name: prop_backend_redis
    image: redis:5.0.6-alpine

volumes:
  prop_docker_volume:
    name: prop_docker_volume
