FROM node:alpine

WORKDIR /usr/src/app
ENV HOME=/usr/src/app

RUN yarn global add @angular/cli
COPY ../frontend/package.json ./
COPY ../frontend/package-lock.json ./
RUN npm install

EXPOSE 4200

USER 1000
