FROM debian:stable-slim

ENV VERSION=7.526

## Install MAFFT.
RUN apt-get update && \
    apt-get install -y build-essential curl && \
    curl https://gitlab.com/sysimm/mafft/-/archive/v$VERSION/mafft-v$VERSION.tar.gz > /tmp/mafft-$VERSION-with-extensions-src.tgz && \
    cd /tmp && tar zxvf mafft-$VERSION-with-extensions-src.tgz && \
    cd /tmp/mafft-v$VERSION/core && \
    sed -e "s/^PREFIX = \/usr\/local/PREFIX = \/opt/" Makefile > Makefile.tmp && \
    mv Makefile.tmp Makefile && \
    make clean && make && make install && \
    cd /tmp && rm -rf mafft-v$VERSION && \
    apt-get purge -y build-essential curl && \
    apt-get autoremove -y

## Set up environment.
# Add /opt/bin to PATH.
ENV PATH /opt/bin:$PATH

WORKDIR /data/
